version: '2.4'
services:
  backend:
    build:
      context: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/opt/app
    restart: always
  frontend:
    build:
      context: ./frontend
    ports:
      - '4050:3000'
    volumes:
      - ./frontend:/opt/app
    restart: always
