version: '2.4'
services:
  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - '8000:8000'
    restart: always
  frontend:
    image: ${FRONTEND_IMAGE}
    env_file: .env
    ports:
      - '80:3000'
    restart: always
